GET http://localhost:3001/api/tasks/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEyOTk0NzZ9.ekTVnDqe53XBihRruWnxiRhph7grdl-yvSxnal4cx5Y

###
GET http://localhost:3001/api/tasks/626d2b03c8cc6ee5ef37ca6a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEzMjE2OTd9.QaF27eyy1S65ka3dZz73z92ZNmrmqfq9e-P-HEr0_XE

###
GET http://localhost:3001/api/tasks/assigned/user/626c3c7ad6caac50d1e85b13
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEzMjE2OTd9.QaF27eyy1S65ka3dZz73z92ZNmrmqfq9e-P-HEr0_XE

###
GET http://localhost:3001/api/tasks/user/626c3c7ad6caac50d1e85b13
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEzMjE2OTd9.QaF27eyy1S65ka3dZz73z92ZNmrmqfq9e-P-HEr0_XE

###
DELETE  http://localhost:3001/api/tasks/626d2b03c8cc6ee5ef37ca6a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEzMjE2OTd9.QaF27eyy1S65ka3dZz73z92ZNmrmqfq9e-P-HEr0_XE

###
POST http://localhost:3001/api/tasks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEyOTk0NzZ9.ekTVnDqe53XBihRruWnxiRhph7grdl-yvSxnal4cx5Y


    {
        "assignedTo": "626c3c7ad6caac50d1e85b13",
        "completed": false,
        "message": "Test Task",
        "dueDate": "2022-04-10T04:00:00.000Z",
        "createdBy": "626d2cfe85dc0698a02d2148"
     }


###
PATCH http://localhost:3001/api/tasks/626d2bf5c8cc6ee5ef37ca6b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEzMjE2OTd9.QaF27eyy1S65ka3dZz73z92ZNmrmqfq9e-P-HEr0_XE

{
    "message": "Submit Advanced Web project"
}

###
POST http://localhost:3001/api/tasks/seed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJWbGFkaW1pciIsImxhc3ROYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.snZEHgy0vMtqifYQyHavTGWLeMpTjoRbfAE1V1Y0ido
