http://localhost:3001

###
GET http://localhost:3001/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEyNjA2MDl9.NLzchGQb_wr6OzDJMgUNAn6KL5qMZU7hyjTf_QsKpvg

###
GET http://localhost:3001/api/users/626c3c7ad6caac50d1e85b13
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZjM2M3YWQ2Y2FhYzUwZDFlODViMTMiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpYXQiOjE2NTEyNjA2MDl9.NLzchGQb_wr6OzDJMgUNAn6KL5qMZU7hyjTf_QsKpvg

###
GET http://localhost:3001/api/users/handle/newpaltz_benevolent

###

DELETE  http://localhost:3001/api/users/625359480694a2e572214278
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJWbGFkaW1pciIsImxhc3ROYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW5lLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.snZEHgy0vMtqifYQyHavTGWLeMpTjoRbfAE1V1Y0ido

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Naveen",
  "handle": "naveen",
  "password": "password",
  "email": "malemn@newpaltz.edu",
  "pic": "https://randomuser.me/api/portraits/men/15.jpg"
}

###
PATCH http://localhost:3001/api/users/2
Content-Type: application/json

{
  "name": "Ramu",
  "password": "secret",
  "email": "suny@newpaltz.edu"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "president@newpaltz.edu",
  "password": "hugo"
}

###
POST http://localhost:3001/api/users/seed
